apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJteXVzZXIiLCJwYXNzd29yZCI6Im15cHdkIiwiZW1haWwiOiJtYXRoYXJvbzg5QGdtYWlsLmNvbSIsImF1dGgiOiJiWGwxYzJWeU9tMTVjSGRrIn19fQ==
kind: Secret
metadata:
  creationTimestamp: "2023-04-14T16:58:23Z"
  name: mycreds
  namespace: default
  resourceVersion: "83989"
  uid: ea336100-8172-4ca7-97f8-7b8f8ed762b7
type: kubernetes.io/dockerconfigjson


# kubectl create secret docker-registry mycreds --docker-username=myuser --docker-password=mypwd --docker-email=matharoo89@gmail.com -o yaml > docker-secret.yaml

# kubectl get secret mycreds -o jsonpath={.data}
# {".dockerconfigjson":"eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJteXVzZXIiLCJwYXNzd29yZCI6Im15cHdkIiwiZW1haWwiOiJtYXRoYXJvbzg5QGdtYWlsLmNvbSIsImF1dGgiOiJiWGwxYzJWeU9tMTVjSGRrIn19fQ=="}%

# echo "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJteXVzZXIiLCJwYXNzd29yZCI6Im15cHdkIiwiZW1haWwiOiJtYXRoYXJvbzg5QGdtYWlsLmNvbSIsImF1dGgiOiJiWGwxYzJWeU9tMTVjSGRrIn19fQ==" | base64 --decode
# {"auths":{"https://index.docker.io/v1/":{"username":"myuser","password":"mypwd","email":"matharoo89@gmail.com","auth":"bXl1c2VyOm15cHdk"}}}%

